### 1.導入需要的函式庫

In [27]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
from sympy import pprint
sp.init_printing()

### 2.主程式

In [30]:
def liorld():
    ### store each vector in the Matrix : Mat , one column for each vector.

    dim = input("Please input the dimension of the Vector space.\n") 
    counter = 0
    dim = int(dim)
    Mat = sp.Matrix( dim*[0] )
    Mat
    v = [0]
    while(1):
            v[0] = input("Please input the first number of the new vector or \"exit\" to stop input.\n")
            if(v[0] == 'exit'):
                 break
            else:
                for i in range(1,dim):
                    new = input("Next number?\n")

                    if(len(v) < dim):
                        v.append(0)

                    v[i] = int(new)

                spv = sp.Matrix(v)
                Mat = Mat.col_insert(1,spv)
                counter+=1
    Mat.col_del(0)
    print('\n\n')
    ### end of input , return Mat--------------------------------

    ### RREF Mat and check which column didn't have a pivot------

    pivots = Mat.rref()[1]
    col_size = Mat.shape[1]



    ### Transpose Mat to make the output easier to read ---------
    Mat_T = Mat.transpose()

    ### Out  put ------------------------------------------------
    print('The max size of the Linearly Independent group is : '
             + str(len(pivots)) + '\n' )

    print("The vectors bellow are Linearly Independent.")
    for i in pivots :
        pprint(Mat_T.row(i))

### 3.測試執行

#### 先舉出若干向量
[1,2,3,4]
[2,4,6,8]
[1,1,1,1]
[1,1,1,3]
[2,2,2,6]

#### 經過計算
##### [1,2,3,4] 和 [2,4,6,8] 以及 [1,1,1,3] 和 [2,2,2,6] 可互相生成
##### 故互線性相依
##### 最大線性獨立集合所含之向量數為 : 3

##### 利用函式計算:

In [31]:
liorld()

Please input the dimension of the Vector space.
4
Please input the first number of the new vector or "exit" to stop input.
1
Next number?
2
Next number?
3
Next number?
4
Please input the first number of the new vector or "exit" to stop input.
2
Next number?
4
Next number?
6
Next number?
8
Please input the first number of the new vector or "exit" to stop input.
1
Next number?
1
Next number?
1
Next number?
1
Please input the first number of the new vector or "exit" to stop input.
1
Next number?
1
Next number?
1
Next number?
3
Please input the first number of the new vector or "exit" to stop input.
2
Next number?
2
Next number?
2
Next number?
6
Please input the first number of the new vector or "exit" to stop input.
exit



The max size of the Linearly Independent group is : 3

The vectors bellow are Linearly Independent.
[2  2  2  6]
[1  1  1  1]
[2  4  6  8]


##### 與預期答案相符

#### 4.反思

這支函式除了不夠簡潔外，最大的問題是在輸入的部分，這種輸入方法在面臨巨量資料時將會非常的難以讀入資料
但是，若要使用它來面對線性代數的期中考那是綽綽有餘，因為此函式很直觀的只要將數字依序輸入就好，不用加
上惱人的中括號和逗號。